apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/images/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
