apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pisio-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - http:
        paths:
          - path: /auth/(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 10000
          - path: /adminer
            pathType: Prefix
            backend:
              service:
                name: adminer
                port:
                  number: 8080
          - path: /music/(.*)
            pathType: Prefix
            backend:
              service:
                name: file-service
                port:
                  number: 11000