apiVersion: v1
kind: Service
metadata:
  name: pisio-redis-service
  namespace: default
spec:
  selector:
    app: pisio-redis
  ports:
    - port: 6379
---
apiVersion: v1
kind: Pod
metadata:
  name: pisio-redis
spec:
  containers:
    - name: redis
      image: redis:5.0.4
      command:
        - redis-server
        - "/redis-master/redis.conf"
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: pisio-redis-config
        items:
          - key: redis-config
            path: redis.conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pisio-redis-config
data:
  redis-config: |
    maxmemory 10mb
    maxmemory-policy allkeys-lru

