apiVersion: v1
kind: Service
metadata:
  name: pdf-service
  namespace: ${k8s.namespace}
spec:
  selector:
    app: pdf-service
  ports:
    - port: 13000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-service
  namespace: ${k8s.namespace}
  labels:
    app: pdf-service
spec:
  replicas: ${pdf-service.replicas}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pdf-service
  template:
    metadata:
      labels:
        app: pdf-service
    spec:
      containers:
        - name: pdf-service
          image: "${docker.image.name}:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 13000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "${spring.profiles.active}"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 13000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 13000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3