server:
  port: ${port:10000}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth-service?useSSL=false&allowPublicKeyRetrieval=true
    username: bojan
    password: bojan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  secret: 9Xk*2*N!U&36gvYT4!
  validity: 3600

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/auth-service?useSSL=false
    username: root
    password: pisiopisio
  jpa:
    show-sql: false